stages: 
  - build
  - deploy 
variables: 
  ANSIBLE_HOST_KEY_CHECKING: "False"

build_files:
  stage: build
  tags: 
    - build
  before_script:
    - echo "195.251.68.21  opencloud2025.duckdns.org" |  tee -a /etc/hosts
  script: 
    - echo "Getting files"
  artifacts:
    name: "playbook-${CI_COMMIT_SHORT_SHA}"
    paths: 
      - loki/
      - node_exporter/
      - ./deploy_loki.yml
      - ./hosts.ini
    expire_in: 1 hour

deploy_playbook:
  stage: deploy
  tags: 
    - ansible
  image: alpine/ansible:latest
  needs: 
    - job: build_files
      artifacts: true
  before_script:
    - echo "running playbooks..."
    - mkdir -p ~/.ssh
    - cp "$SSH_KEY_MGR" ~/.ssh/mgr_id_rsa
    - cp "$SSH_KEY_REVERSE" ~/.ssh/reverse_id_rsa
    - cp "$SSH_KEY_SK" ~/.ssh/sk_id_rsa
    - cp "$SSH_KEY_RUNNER" ~/.ssh/runner_id_rsa

    - chmod 600 ~/.ssh/*

  script:
    - ansible --version 
    - ansible-playbook deploy_loki.yml -i hosts.ini
    - ansible-playbook deploy_node.yml -i hosts.ini

  environment: 
    name: production 
  only: 
    - main
