- hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Update python3 to v3.9
      raw: "apt-get update && apt-get install -y software-properties-common && add-apt-repository -y ppa:deadsnakes/ppa && apt-get install -y python3.9"
      changed_when: false
  tasks:

    - name: set ansible interpreter to python3.9
      set_fact:
        ansible_python_interpreter: /usr/bin/python3.9
    - name: gather facts
      setup: 

    - name: check if pip is installed
      command: which pip
      register: pip_check
      ignore_errors: yes
    - name: install pip
      raw: "apt install python3-pip -y && apt get update -y"

      when: pip_check.rc != 0
    - name: install python docker
      pip: 
        name: "docker"
      
    - name: Get info on container state
      docker_container_info:
        name: node_exporter
      register: result
    - name: Check container existance
      debug:
        msg: "The container {{'exists' if result.exists else 'does not exist'}}"
    - name: make node_exporter directory
      shell: mkdir -p /home/ubuntu/node_exporter
      when: not result.exists
    - name: copy compose yml
      copy: 
        src: ./node_exporter/docker-compose.yml
        dest: /home/ubuntu/node_exporter/docker-compose.yml
      when: not result.exists
    - name: docker compose up
      shell: docker compose -f /home/ubuntu/node_exporter/docker-compose.yml up -d 
      args:
        chdir: /home/ubuntu/node_exporter
      when: not result.exists

