- hosts: all
  become: yes
  tasks:
    - name: check if pip is installed
      command: which pip
      register: pip_check
      ignore_errors: yes
    - name: install pip
      apt: 
        name: python3-pip
        state: present
        update_cache: yes
      when: pip_check.rc != 0
    - name: install python docker
      pip: 
        name: "docker"
      

